apiVersion: v1
kind: Secret
metadata:
  name: secret-postgres
type: Opaque
# emulating secret using base64
data:
  POSTGRES_USER: ZnJoYW4=
  POSTGRES_PASSWORD: ZGJfcG9zdGdyZXM=
  POSTGRES_DB: ZW1wbG95ZWVzX2Ri
