# service-gke.yml
apiVersion: v1
kind: Service
metadata:
  name: empl-api
spec:
  type: LoadBalancer
  selector:
    app: api-empl
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      